-
  branches:
    only:
      - master

  version: 4.0.0

  install:
    - ps : .\environment-install.ps1

  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'

  os: Visual Studio 2017

  before_build:
    - ps : .\build-before_build.ps1

  build:
    parallel: true
    verbosity: normal
    publish_nuget: true

  configuration: Release

  test:
    assemblies:
      - '**\*.Tests.dll'
      - '**\*.FunctionalTests.dll'
      - '**\*..IntegrationTests.dll'

  deploy:
    - provider: Environment
      name: Liberis NuGet

    - provider: Environment
      name: Liberis MyGet

-
  branches:
    except:
      - master

  version: 4.0.0-{branch}{build}

  install:
    - ps : .\environment-install.ps1

  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
    informational_version: '{version}'

  os: Visual Studio 2017

  before_build:
    - ps : .\build-before_build.ps1

  build:
    parallel: true
    verbosity: normal
    publish_nuget: true

  configuration: Release

  test:
    assemblies:
      - '**\*.Tests.dll'
      - '**\*.FunctionalTests.dll'
      - '**\*..IntegrationTests.dll'
